/**
 * Hand-written API functions for participant endpoints.
 * These are NOT generated by Orval — they live here until the OpenAPI spec
 * is regenerated and Orval picks them up natively.
 */

export type SyncParticipantsBody = {
  guildId: string;
  participants: Array<{ discordUserId: string; discordName: string }>;
};

export type SyncParticipants200 = {
  status: string;
  data: { campaignId: string; upserted: number };
};

export const syncParticipants = async (
  body: SyncParticipantsBody,
  options?: RequestInit,
): Promise<SyncParticipants200> => {
  const res = await fetch(
    `${process.env.BACKEND_URL ?? 'http://localhost:3000'}/api/v1/bot/sync-participants`,
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(body),
    },
  );
  const text = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!text) {
    throw new Error(`Expected sync participants response body, received ${res.status}`);
  }

  return JSON.parse(text) as SyncParticipants200;
};

export type RemoveParticipantParams = {
  guildId: string;
  discordUserId: string;
};

export type RemoveParticipant200 = {
  status: string;
  deleted: boolean;
};

export const removeParticipant = async (
  { guildId, discordUserId }: RemoveParticipantParams,
  options?: RequestInit,
): Promise<RemoveParticipant200> => {
  const res = await fetch(
    `${process.env.BACKEND_URL ?? 'http://localhost:3000'}/api/v1/bot/participant/${guildId}/${discordUserId}`,
    {
      ...options,
      method: 'DELETE',
    },
  );
  const text = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!text) {
    throw new Error(`Expected remove participant response body, received ${res.status}`);
  }

  return JSON.parse(text) as RemoveParticipant200;
};
