import { index, layout, route, type RouteConfig } from '@react-router/dev/routes';

export default [
  route('auth', './routes/auth.tsx'),
  route('logout', './routes/logout.tsx'),
  route('player/campaigns/:campaignId/sheet', './routes/player-sheet.tsx'),
  route('player/campaigns/:campaignId/journal', './routes/player-journal.tsx'),
  route('player/campaigns/:campaignId/npcs/:npcId', './routes/player-npc.tsx'),
  route('demo/player/sheet', './routes/player-sheet.tsx', { id: 'demo-player-sheet' }),
  route('demo/player/journal', './routes/player-journal.tsx', { id: 'demo-player-journal' }),
  route('demo/player/npcs/:npcId', './routes/player-npc.tsx', { id: 'demo-player-npc' }),
  layout('./routes/demo-layout.tsx', { id: 'demo-layout' }, [
    route('demo', './routes/play.tsx', { id: 'demo-play' }),
    route('demo/setup', './routes/setup.tsx', { id: 'demo-setup' }),
    route('demo/setup/events/new', './routes/setup-event.tsx', { id: 'demo-setup-event-new' }),
    route('demo/setup/events/:eventId', './routes/setup-event.tsx', { id: 'demo-setup-event' }),
    route('demo/setup/npcs/new', './routes/setup-npc.tsx', { id: 'demo-setup-npc-new' }),
    route('demo/setup/npcs/:npcId', './routes/setup-npc.tsx', { id: 'demo-setup-npc' }),
    route('demo/setup/quests/new', './routes/setup-quest.tsx', { id: 'demo-setup-quest-new' }),
    route('demo/setup/quests/:questId', './routes/setup-quest.tsx', { id: 'demo-setup-quest' }),
    route('demo/setup/lore/new', './routes/setup-lore.tsx', { id: 'demo-setup-lore-new' }),
    route('demo/setup/lore/:loreId', './routes/setup-lore.tsx', { id: 'demo-setup-lore' }),
    route('demo/npcs', './routes/npcs.tsx', { id: 'demo-npcs' }),
    route('demo/lore', './routes/lore.tsx', { id: 'demo-lore' }),
    route('demo/participants', './routes/participants.tsx', { id: 'demo-participants' }),
    route('demo/log', './routes/log.tsx', { id: 'demo-log' }),
  ]),
  layout('./routes/war-room-layout.tsx', [
    index('./routes/play.tsx'),
    route('setup', './routes/setup.tsx'),
    route('setup/events/new', './routes/setup-event.tsx', { id: 'setup-event-new' }),
    route('setup/events/:eventId', './routes/setup-event.tsx', { id: 'setup-event' }),
    route('setup/npcs/new', './routes/setup-npc.tsx', { id: 'setup-npc-new' }),
    route('setup/npcs/:npcId', './routes/setup-npc.tsx', { id: 'setup-npc' }),
    route('setup/quests/new', './routes/setup-quest.tsx', { id: 'setup-quest-new' }),
    route('setup/quests/:questId', './routes/setup-quest.tsx', { id: 'setup-quest' }),
    route('setup/lore/new', './routes/setup-lore.tsx', { id: 'setup-lore-new' }),
    route('setup/lore/:loreId', './routes/setup-lore.tsx', { id: 'setup-lore' }),
    route('npcs', './routes/npcs.tsx'),
    route('lore', './routes/lore.tsx'),
    route('participants', './routes/participants.tsx'),
    route('participants/:charId', './routes/participant-sheet.tsx'),
    route('log', './routes/log.tsx'),
  ]),
] satisfies RouteConfig;
